#=======================================================================================
# Global Config
#=======================================================================================
spring:
  application:
    name: adminservice
  profiles:
    active: "dev"
  security:
    basic:
      enabled: true
    oauth2:
      client:
        registration:
          custom:
            authorization-grant-type: client_credentials
            client-id: callcentre-admin-project
            client-secret: 'b3c51801-641b-4c7e-93ad-1b5d1acae556'
            provider: customprovider
        provider:
          customprovider:
            token-uri: https://keycloak.auth.betalab.rp.bt.com/auth/realms/master/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.auth.betalab.rp.bt.com/auth/realms/master

# Actuator endpoints
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /_/
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
  exposure.include: '*'
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST, PUT
    allowed-headers: '*'

adminservice:
  queueAddress: SETINENV
  queuePortString: SETINENV
  queueUser: SETINENV
  queuePassword: SETINENV
  queueName: SETINENV
  loadGeneratorUrl: SETINENV
  callReportingUrl: SETINENV
  kubernetesNameSpace: SETINENV
  workerImage: SETINENV
  myReportingUrl: SETINENV
  myReportingUrlUser: SETINENV
  myReportingUrlPassword: SETINENV

---
#=======================================================================================
# Development Profile Config
#=======================================================================================
spring:
  profiles: dev
server:
  port: 8080

adminservice:
  queueAddress: digitaltwin-rabbitmq.project-call-centre.svc.cluster.local
  queuePortString: 5672
  queueUser: user
  queuePassword: 6MLtpE3vhdGkYCT8
  queueName: calls
  loadGeneratorUrl: https://localhost:8081/api/v1/generate
  callReportingURL: https://dashboard-service.dashboard.callcentre.betalab.rp.bt.com/api/v1/report
  kubernetesNameSpace: project-call-centre
  workerImage: registry.docker.nat.bt.com/betalab-callcentre-digitaltwin/callcentre-digitaltwin-worker:6f8a43837ec68ec277197b625e18103a481f347a
  myReportingURL: https://admin-service.digitaltwin.callcentre.betalab.rp.bt.com/api/v1/report
  myReportingUser: worker
  myReportingPassword: w0rk3rP4ssW0rd


---
#=======================================================================================
# Production ProfileConfig - ALL CONFIG SHOULD BE PASSED AS ENV VARIABLES
#=======================================================================================
spring:
  profiles: production
server:
  port: 8080